### ISSUE TITLE
Test Scripts Fail

### ISSUE THREAD

**Issue by ek051698** [DedalusProject/dedalus#121] opened 2021-02-22 18:55 UTC
I've installed dedalus using conda and run into an issue with the test scripts failing. 
The tasks that failed were
- test_gaussian_free[Hermite-128-float64]
- test_qho_dense_evp[Hermite-128-complex128]
- test_gaussian_free[Hermite-128-complex128]

All 3 failed tasks gave the error message 
TypeError: 'numpy.float128' object cannot be interpreted as an integer
anaconda3/envs/dedalus/lib/python3.8/site-packages/scipy/special/_basic.py:2352: TypeError

**Comment by kburns** [comment] 2021-02-22 20:56
Duplicate of #110.

**Closed by kburns** 2021-02-22 20:56 UTC
Labels: duplicate
